matches:
  - trigger: ":todate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"
  - trigger: ":s-yday"
    replace: "{{start_yesterday}}"
    vars:
      - name: start_yesterday
        type: shell
        params:
          cmd: ~/.config/espanso/match/start_of.py yesterday
  - trigger: ":s-today"
    replace: "{{start_today}}"
    vars:
      - name: start_today
        type: shell
        params:
          cmd: ~/.config/espanso/match/start_of.py today
  - trigger: ":s-tomo"
    replace: "{{start_tomorrow}}"
    vars:
      - name: start_tomorrow
        type: shell
        params:
          cmd: ~/.config/espanso/match/start_of.py tomorrow
